---

- name: Install tomcat7 ignoring startup error due to java path issues
  apt: name=tomcat7 state=present update_cache=yes
  ignore_errors: yes

- lineinfile: 
    dest: /etc/default/tomcat7
    line: "JAVA_HOME={{oracle_java_home}}"
  
- service: name=tomcat7 state=restarted